name: VPS Runner

on:
  workflow_dispatch:

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15,16,17,18,19,20,
            21,22,23,24,25,26,27,28,29,30,
            31,32,33,34,35,36,37,38,39,40,
            41,42,43,44,45,46,47,48,49,50]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Miniconda
        run: |
          export LANG=C LC_ALL=C
          wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"

      - name: Setup Python environment
        run: |
          conda init bash
          source ~/.bashrc
          conda create -y -n vpsenv python=3.10
          source activate vpsenv
          pip install requests

      - name: Run VPS Script
        run: |
          chmod +x *
          python vps.py
